[package]
name = "ridemap"
version = "0.0.1"
authors = ["G. Endignoux <ggendx@gmail.com>"]
license = "MIT"
repository = "https://github.com/gendx/ridemap"
readme = "README.md"
exclude = [".github/*"]
edition = "2021"
rust-version = "1.92.0"

[dependencies]
anyhow = "1.0.102"
cairo-rs = { version = "0.22.0", features = ["freetype"], optional = true }
clap = { version = "4.6.1", features = ["derive"] }
env_logger = "0.11.10"
futures = { version = "0.3.32", default-features = false, features = ["std", "async-await"] }
freetype-rs = { version = "0.38.0", optional = true }
geojson = { version = "1.0.0" }
gtk4 = { version = "0.11.3", optional = true }
image = { version = "0.25.10", default-features = false, features = ["png"] }
log = "0.4.30"
piston_window = { version = "0.147.0", optional = true }
rand = "0.10.1"
regex = { version = "1.12.3", default-features = false, features = ["std"] }
reqwest = { version = "0.13.4", features = ["json", "query"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde-xml-rs = "0.8.2"
tokio = { version = "1.52.3", features = ["rt-multi-thread"] }

[features]
default = ["backend_gtk4"]
backend_gtk4 = ["dep:gtk4", "dep:cairo-rs", "dep:freetype-rs"]
backend_piston = ["dep:piston_window"]

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]
