on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.70.0  # MSRV
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Install development packages for GTK-4
        run: sudo apt install -y libgtk-4-dev --no-install-recommends
      - name: Build with Piston backend
        run: cargo build --verbose --no-default-features --features backend_piston
      - name: Build with GTK-4 backend
        run: cargo build --verbose --no-default-features --features backend_gtk4
