on: [push, pull_request]
name: Build
jobs:
  build:
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.74.0  # MSRV
        backend:
          - gtk4
          - piston
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Create Cargo.lock file
        run: cargo generate-lockfile
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ matrix.backend }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ matrix.backend }}-${{ hashFiles('Cargo.toml') }}
            cargo-registry-${{ matrix.backend }}

      - name: Check Cargo version
        run: cargo -V > cargo.version.txt
      - name: Cache Cargo target
        uses: actions/cache@v4
        with:
          path: target
          key: cargo-target-debug-${{ matrix.backend }}-${{ hashFiles('cargo.version.txt') }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-target-debug-${{ matrix.backend }}-${{ hashFiles('cargo.version.txt') }}-${{ hashFiles('Cargo.toml') }}
            cargo-target-debug-${{ matrix.backend }}-${{ hashFiles('cargo.version.txt') }}

      - name: Install development packages for GTK-4
        if: ${{ matrix.backend == 'gtk4' }}
        run: sudo apt install -y libgtk-4-dev --no-install-recommends

      - name: Build
        run: cargo build --verbose --no-default-features --features backend_${{ matrix.backend }}
