on: [push, pull_request]
name: Lints on nightly toolchain
jobs:
  clippy:
    strategy:
      matrix:
        backend:
          - gtk4
          - piston
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Create Cargo.lock file
        run: cargo generate-lockfile
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-registry-${{ hashFiles('Cargo.toml') }}
            cargo-registry

      - name: Check Cargo version
        run: cargo -V > cargo.version.txt
      - name: Cache Cargo target
        uses: actions/cache/restore@v3
        with:
          path: target
          key: cargo-target-debug-${{ matrix.backend }}-${{ hashFiles('cargo.version.txt') }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-target-debug-${{ matrix.backend }}-${{ hashFiles('cargo.version.txt') }}-${{ hashFiles('Cargo.toml') }}
            cargo-target-debug-${{ matrix.backend }}-${{ hashFiles('cargo.version.txt') }}

      - name: Install development packages for GTK-4
        if: ${{ matrix.backend == 'gtk4' }}
        run: sudo apt install -y libgtk-4-dev --no-install-recommends

      - name: Check Clippy lints
        run: cargo clippy --verbose --no-default-features --features backend_${{ matrix.backend }}
      - name: Check Clippy lints on tests
        run: cargo clippy --verbose --no-default-features --features backend_${{ matrix.backend }} --tests
