on: [push, pull_request]
name: Lints on nightly toolchain
jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Install development packages for GTK-4
        run: sudo apt install -y libgtk-4-dev --no-install-recommends
      - name: Check Clippy lints
        run: cargo clippy --verbose
      - name: Check Clippy lints on tests
        run: cargo clippy --verbose --tests
