on: [push, pull_request]
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: Tests in debug mode
        run: cargo test --verbose
      - name: Tests in release mode
        run: cargo test --release --verbose
